# Generated by Django 4.2.16 on 2024-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_water_requi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_requi',
            name='area_ha',
            field=models.FloatField(null=True),
        ),
    ]
